# Census 2020 response rates

## NewsCounts

In [1]:
import pandas as pd
import numpy as np
import requests
import sys
from datetime import date

In [2]:
today = date.today()

states = pd.read_csv("Data/state_codes.txt",sep=" 	", engine='python')
counties = pd.read_csv("Data/county_codes.txt",sep=" 	", engine='python')

In [3]:
key = "124e1b1d5ceca3b46b3f6bd97d95ea8d4d780e28"

In [4]:
url = f"https://api.census.gov/data/2020/dec/responserate?get=GEO_ID,CAVG&for=state:*&key={key}"
response = requests.get(url)
if response:
    print('State: Success!')
else:
    print('State: An error has occurred.')
    sys.exit("State: "+response.text)

State: Success!

Create data frame from json.

In [5]:
state_df = pd.DataFrame.from_records(response.json()[1:])

state_df.columns = ["GEO_ID","CAVG","state"]
state_df['state'] = state_df.state.astype(int)

state_df['state_name'] = state_df.state.map(states.set_index('code')['state'])

state_df['state_short'] = state_df.state.map(states.set_index('code')['state_code'])

columns = list(state_df.columns)
state_df["date"] = str(today)

state_df = state_df[["date"]+columns]
state_df.sort_values(by="state",inplace=True)
state_df = state_df.reset_index(drop=True)
state_df

          date       GEO_ID  CAVG  state      state_name state_short
0   2020-03-20  0400000US01  14.7      1         Alabama          AL
1   2020-03-20  0400000US02   2.5      2          Alaska          AK
2   2020-03-20  0400000US04   9.9      4         Arizona          AZ
3   2020-03-20  0400000US05    14      5        Arkansas          AR
4   2020-03-20  0400000US06  12.7      6      California          CA
5   2020-03-20  0400000US08  10.5      8        Colorado          CO
6   2020-03-20  0400000US09  12.9      9     Connecticut          CT
7   2020-03-20  0400000US10  14.9     10        Delaware          DE
8   2020-03-20  0400000US11  14.8     11             NaN         NaN
9   2020-03-20  0400000US12  13.1     12         Florida          FL
10  2020-03-20  0400000US13  10.9     13         Georgia          GA
11  2020-03-20  0400000US15   6.4     15          Hawaii          HI
12  2020-03-20  0400000US16  14.3     16           Idaho          ID
13  2020-03-20  0400000US17    19     17        Illinois          IL
14  2020-03-20  0400000US18  17.2     18         Indiana          IN
15  2020-03-20  0400000US19  20.7     19            Iowa          IA
16  2020-03-20  0400000US20    18     20          Kansas          KS
17  2020-03-20  0400000US21  13.6     21        Kentucky          KY
18  2020-03-20  0400000US22  11.8     22       Louisiana          LA
19  2020-03-20  0400000US23  11.5     23           Maine          ME
20  2020-03-20  0400000US24  14.3     24        Maryland          MD
21  2020-03-20  0400000US25    14     25   Massachusetts          MA
22  2020-03-20  0400000US26  15.2     26        Michigan          MI
23  2020-03-20  0400000US27  17.7     27       Minnesota          MN
24  2020-03-20  0400000US28  14.2     28     Mississippi          MS
25  2020-03-20  0400000US29  15.6     29        Missouri          MO
26  2020-03-20  0400000US30   7.6     30         Montana          MT
27  2020-03-20  0400000US31  17.2     31        Nebraska          NE
28  2020-03-20  0400000US32  10.5     32          Nevada          NV
29  2020-03-20  0400000US33  11.1     33   New Hampshire          NH
30  2020-03-20  0400000US34  13.5     34      New Jersey          NJ
31  2020-03-20  0400000US35   7.8     35      New Mexico          NM
32  2020-03-20  0400000US36  12.9     36        New York          NY
33  2020-03-20  0400000US37  11.1     37  North Carolina          NC
34  2020-03-20  0400000US38  13.4     38    North Dakota          ND
35  2020-03-20  0400000US39  16.1     39            Ohio          OH
36  2020-03-20  0400000US40  11.1     40        Oklahoma          OK
37  2020-03-20  0400000US41  12.2     41          Oregon          OR
38  2020-03-20  0400000US42  14.8     42    Pennsylvania          PA
39  2020-03-20  0400000US44  17.2     44    Rhode Island          RI
40  2020-03-20  0400000US45  12.5     45  South Carolina          SC
41  2020-03-20  0400000US46  13.2     46    South Dakota          SD
42  2020-03-20  0400000US47  15.3     47       Tennessee          TN
43  2020-03-20  0400000US48     9     48           Texas          TX
44  2020-03-20  0400000US49   8.6     49            Utah          UT
45  2020-03-20  0400000US50  11.5     50         Vermont          VT
46  2020-03-20  0400000US51  15.6     51        Virginia          VA
47  2020-03-20  0400000US53  12.3     53      Washington          WA
48  2020-03-20  0400000US54   8.7     54   West Virginia          WV
49  2020-03-20  0400000US55  16.7     55       Wisconsin          WI
50  2020-03-20  0400000US56  10.9     56         Wyoming          WY
51  2020-03-20  0400000US72     0     72     Puerto Rico          PR

In [6]:
state_df.to_csv("Data/sates_response_rates.csv",mode = 'a', header = False, index = False)

I do the same for all counties:

In [7]:
data=[]
url = f"https://api.census.gov/data/2020/dec/responserate?get=GEO_ID,CAVG&for=county:*&key={key}"
response = requests.get(url)
if response:
    print('County: Success!')
    data = response.json()
else:
    print('An error has occurred.')
    sys.exit("County: "+response.text)

County: Success!

In [8]:
county_df = pd.DataFrame.from_records(data[1:])
county_df.columns = data[0]
county_df['state_county'] = county_df.state + county_df.county
county_df['state_county'] = county_df.state_county.astype(int)
county_df['state'] = county_df.state.astype(int)

county_df['state_name'] = county_df.state.map(states.set_index('code')['state'])
county_df['state_short'] = county_df.state.map(states.set_index('code')['state_code'])

county_df['county_name'] = county_df.state_county.map(counties.set_index('code')['county'])

columns = list(county_df.columns)
county_df["date"] = str(today)

county_df = county_df[["date"]+columns]
county_df.sort_values(by=["state_county"],inplace=True)
county_df = county_df.reset_index(drop=True)
county_df

,date,GEO_ID,CAVG,state,county,state_county,state_name,state_short,county_name
0,2020-03-20,0500000US01001,18.4,1,001,1001,Alabama,AL,Autauga
1,2020-03-20,0500000US01003,13.1,1,003,1003,Alabama,AL,Baldwin
2,2020-03-20,0500000US01005,13.6,1,005,1005,Alabama,AL,Barbour
3,2020-03-20,0500000US01007,16.4,1,007,1007,Alabama,AL,Bibb
4,2020-03-20,0500000US01009,16.8,1,009,1009,Alabama,AL,Blount
...,...,...,...,...,...,...,...,...,...
3211,2020-03-20,0500000US72145,0,72,145,72145,Puerto Rico,PR,Vega Baja
3212,2020-03-20,0500000US72147,0,72,147,72147,Puerto Rico,PR,Vieques
3213,2020-03-20,0500000US72149,0,72,149,72149,Puerto Rico,PR,Villalba
3214,2020-03-20,0500000US72151,0,72,151,72151,Puerto Rico,PR,Yabucoa
3215,2020-03-20,0500000US72153,0,72,153,72153,Puerto Rico,PR,Yauco

In [9]:
county_df.to_csv("Data/counties_response_rates.csv",mode = 'a', header = False, index = False)

I do the same for all tracts:

In [10]:
data=[]
c=0
for i in range(len(state_df)):
    s = state_df.iloc[i,:]
    if s.state <10:
        num = f"0{s.state}"
    else:
        num = s.state
    url = f"https://api.census.gov/data/2020/dec/responserate?get=GEO_ID,CAVG&for=tract:*&in=state:{num}&key={key}"
    response = requests.get(url)
    if  not response:
        print('Tract: An error has occurred.')
        print(response.text)
        sys.exit("Tract: "+response.text)
    else:
        start = 0 if c==0 else 1
        data = data + response.json()[start:]
        c=c+1
        
print("Tract: Done!")

Tract: Done!

In [11]:
tract_df = pd.DataFrame.from_records(data[1:])
tract_df.columns = data[0]
tract_df['state_county'] = tract_df.state + tract_df.county
tract_df['state_county'] = tract_df.state_county.astype(int)
tract_df['state'] = tract_df.state.astype(int)

tract_df['state_name'] = tract_df.state.map(states.set_index('code')['state'])
tract_df['state_short'] = tract_df.state.map(states.set_index('code')['state_code'])

tract_df['county_name'] = tract_df.state_county.map(counties.set_index('code')['county'])

columns = list(tract_df.columns)
tract_df["date"] = str(today)

tract_df = tract_df[["date"]+columns]
tract_df.sort_values(by=["state_county","tract"],inplace=True)
tract_df = tract_df.reset_index(drop=True)
tract_df

,date,GEO_ID,CAVG,state,county,tract,state_county,state_name,state_short,county_name
0,2020-03-20,1400000US01001020100,None,1,001,020100,1001,Alabama,AL,Autauga
1,2020-03-20,1400000US01001020200,None,1,001,020200,1001,Alabama,AL,Autauga
2,2020-03-20,1400000US01001020300,None,1,001,020300,1001,Alabama,AL,Autauga
3,2020-03-20,1400000US01001020400,None,1,001,020400,1001,Alabama,AL,Autauga
4,2020-03-20,1400000US01001020501,None,1,001,020501,1001,Alabama,AL,Autauga
...,...,...,...,...,...,...,...,...,...,...
84088,2020-03-20,1400000US72153750501,None,72,153,750501,72153,Puerto Rico,PR,Yauco
84089,2020-03-20,1400000US72153750502,None,72,153,750502,72153,Puerto Rico,PR,Yauco
84090,2020-03-20,1400000US72153750503,None,72,153,750503,72153,Puerto Rico,PR,Yauco
84091,2020-03-20,1400000US72153750601,None,72,153,750601,72153,Puerto Rico,PR,Yauco
84092,2020-03-20,1400000US72153750602,None,72,153,750602,72153,Puerto Rico,PR,Yauco

In [12]:
tract_df.to_csv("Data/tracts_response_rates.csv",mode = 'a', header = False,  index = False)